[package]
name = "qcore-bindings"
version = "0.7.0"
authors = ["Golanr Mordadi <golnarmordadi@gmail.com>"]
edition = "2018"

[dependencies]
cw-storage-plus = "1.0.1"
cosmwasm-schema = "1.1.0"
cosmwasm-std = "1.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
