// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: outbe/gemmint/minted.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Minted struct {
	TotalMinted cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=total_minted,json=totalMinted,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_minted"`
	Block       uint64                      `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	BlockMinted cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=block_minted,json=blockMinted,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"block_minted"`
}

func (m *Minted) Reset()         { *m = Minted{} }
func (m *Minted) String() string { return proto.CompactTextString(m) }
func (*Minted) ProtoMessage()    {}
func (*Minted) Descriptor() ([]byte, []int) {
	return fileDescriptor_41de6b822b90ad6d, []int{0}
}
func (m *Minted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Minted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Minted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Minted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Minted.Merge(m, src)
}
func (m *Minted) XXX_Size() int {
	return m.Size()
}
func (m *Minted) XXX_DiscardUnknown() {
	xxx_messageInfo_Minted.DiscardUnknown(m)
}

var xxx_messageInfo_Minted proto.InternalMessageInfo

func (m *Minted) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func init() {
	proto.RegisterType((*Minted)(nil), "outbe.gemmint.Minted")
}

func init() { proto.RegisterFile("outbe/gemmint/minted.proto", fileDescriptor_41de6b822b90ad6d) }

var fileDescriptor_41de6b822b90ad6d = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xca, 0x2f, 0x2d, 0x49,
	0x4a, 0xd5, 0x4f, 0x4f, 0xcd, 0xcd, 0xcd, 0xcc, 0x2b, 0xd1, 0x07, 0x11, 0xa9, 0x29, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0xbc, 0x60, 0x39, 0x3d, 0xa8, 0x9c, 0x94, 0x48, 0x7a, 0x7e, 0x7a,
	0x3e, 0x58, 0x46, 0x1f, 0xc4, 0x82, 0x28, 0x92, 0x92, 0x4c, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0x8e,
	0x87, 0x48, 0x40, 0x38, 0x50, 0x29, 0xc1, 0xc4, 0xdc, 0xcc, 0xbc, 0x7c, 0x7d, 0x30, 0x09, 0x11,
	0x52, 0x3a, 0xc5, 0xc8, 0xc5, 0xe6, 0x0b, 0xb6, 0x43, 0x28, 0x84, 0x8b, 0xa7, 0x24, 0xbf, 0x24,
	0x31, 0x27, 0x1e, 0x62, 0xa7, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xa7, 0x93, 0xe1, 0x89, 0x7b, 0xf2,
	0x0c, 0xb7, 0xee, 0xc9, 0x4b, 0x43, 0x4c, 0x2a, 0x4e, 0xc9, 0xd6, 0xcb, 0xcc, 0xd7, 0xcf, 0x4d,
	0x2c, 0xc9, 0xd0, 0xf3, 0x49, 0x4d, 0x4f, 0x4c, 0xae, 0x74, 0x49, 0x4d, 0xbe, 0xb4, 0x45, 0x97,
	0x0b, 0x6a, 0x91, 0x4b, 0x6a, 0x72, 0x10, 0x37, 0xd8, 0x18, 0xa8, 0xa9, 0x22, 0x5c, 0xac, 0x49,
	0x39, 0xf9, 0xc9, 0xd9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x10, 0x0e, 0xc8, 0x2e, 0x30,
	0x03, 0x66, 0x17, 0x33, 0xd9, 0x76, 0x81, 0x8d, 0x81, 0xd8, 0xe5, 0xe4, 0x7a, 0xe2, 0x91, 0x1c,
	0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1,
	0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0xda, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9,
	0xf9, 0xb9, 0xfa, 0x90, 0x00, 0x06, 0x93, 0xba, 0x79, 0xf9, 0x29, 0xa9, 0xfa, 0x15, 0xf0, 0xd0,
	0x2e, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0x07, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x66, 0xc2, 0x14, 0xc0, 0x8b, 0x01, 0x00, 0x00,
}

func (m *Minted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Minted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Minted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BlockMinted.Size()
		i -= size
		if _, err := m.BlockMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMinted(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Block != 0 {
		i = encodeVarintMinted(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.TotalMinted.Size()
		i -= size
		if _, err := m.TotalMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMinted(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMinted(dAtA []byte, offset int, v uint64) int {
	offset -= sovMinted(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Minted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalMinted.Size()
	n += 1 + l + sovMinted(uint64(l))
	if m.Block != 0 {
		n += 1 + sovMinted(uint64(m.Block))
	}
	l = m.BlockMinted.Size()
	n += 1 + l + sovMinted(uint64(l))
	return n
}

func sovMinted(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMinted(x uint64) (n int) {
	return sovMinted(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Minted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMinted
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Minted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Minted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinted
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinted
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMinted
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMinted
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMinted(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMinted
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMinted(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMinted
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMinted
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMinted
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMinted
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMinted
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMinted        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMinted          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMinted = fmt.Errorf("proto: unexpected end of group")
)
